CREATE TABLE TB_PESSOAS(
	
	PESSOA_ID BIGINT NOT NULL AUTO_INCREMENT,
	PESSOA_EXTERNAL_ID UUID UNIQUE NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	DATA_DE_NASCIMENTO DATE NOT NULL,
	DATA_DA_CRIACAO TIMESTAMP,
	DATA_DA_ULTIMA_ATUALIZACAO TIMESTAMP,
	
	PRIMARY KEY(PESSOA_ID)
);