
CREATE TABLE TB_PESSOAS_ENDERECOS(
PESSOA_ID BIGINT NOT NULL,
ENDERECO_ID BIGINT NOT NULL,
FOREIGN KEY (PESSOA_ID) REFERENCES TB_PESSOAS (PESSOA_ID),
FOREIGN KEY (ENDERECO_ID) REFERENCES TB_ENDERECOS (ENDERECO_ID)
);